Repository 100DaysOfCloud/100DaysOfCloudFrontend, pull requests merged in 2020-07, with the labels that each got.

#4 Refactor: change footer from class to function based component
  src/components/Footer.js
Labels: Refactor

#13 ProfileBadge component first draft
  src/components/ProfileBadge/ProfileBadge.js
  src/components/ProfileBadge/ProfileComponents.js
  src/pages/profileExample.js
  src/styles.css
Labels: enhancement

#15 Add Issue/Pull Request templates
  .gitbhub/ISSUE_TEMPLATE/1. New Feature.md
  .gitbhub/ISSUE_TEMPLATE/2. Bug report.md
  .gitbhub/PULL_REQUEST_TEMPLATE.md
  src/components/Header.js
Labels: documentation

#21 Refactor Article Thumbnail to use functional component
  src/components/ArticleThumbnail.js
Labels: Refactor

#22 Major refactor for multiple components [Closes #1]
  src/components/AccountDropdown.js
  src/components/BackButton.js
  src/components/FeaturedArticle.js
  src/components/Footer.js
  src/components/NewsCarousel.js
Labels: Refactor

#18 Rules and CoC page generated from markdown file. Closes #11
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/markdown-pages/rules.md
  src/rules.css
  src/styles.css
  src/templates/rules.js
Labels: enhancement

#24 add: mock user data
  src/data/users1.json
  src/data/users2.json
Labels: enhancement
